### PR TITLE
New mapper: Bnrom

### PR DESCRIPTION
**Pull request by tedsteen**
I was missing the bnrom mapper for the multi-region version of our game.
I started implementing it and quickly noticed that I am way too unexperienced with the details around memory mapping and mirroring in tetanes 😅

It works for our game, but I have honestly no idea if it is implemented correctly.
My biggest unknown is around the mirroring, what could cause it to change, how should it relate to mapping memory?

If you have the time and think that this is a good start perhaps you could take it from here?

I used this as inspiration: https://github.com/zeta0134/rustico/blob/master/core/src/mmc/bnrom.rs

### CODE REVIEW

**Comment by lukexor** [comment]
This looks like a great start! I'll take a look over the bnrom docs and just verify everything but in general switchable mirroring for a mapper is just controlled via a register and it only really gets super complicated if four screen mirroring is supported as that requires the mapper to manage the memory reads differently instead of just letting the PPU handle it

**Comment by lukexor** [comment]
I'll merge and then test it out some more, making any tweaks needed. Thanks for the contribution!

**Comment by lukexor** [comment]
It was mostly good - just had to adjust to fixed mirroring based on iNES header, allow 8MB PRG-ROM and support the NINA-001 variant based on the presence of CHR-ROM.

**Comment by tedsteen** [comment]
Awesome, works great. Thank you!

**Pull request merged**
